apiVersion: v1
kind: Service
metadata:
  name: notitia-ocpu-service
spec:
  ports:
  - port: 31003
    nodePort: 31003
    targetPort: ocpu-port
    protocol: TCP
  selector:
    app: notitia-ocpu
  type: NodePort
